CREATE TABLE cowsanctuaries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    address TEXT,
    phone VARCHAR(20),
    organizationType VARCHAR(100),
    organizationTypeOther VARCHAR(255),
    registeredOrgName VARCHAR(255),
    founders VARCHAR(255),
    founderContact VARCHAR(255),
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    visitAddress TEXT,
    locationLink VARCHAR(255),
    website VARCHAR(255),
    socialLinks VARCHAR(255),
    hostingdeclaration BOOLEAN,
    eligibilitydeclaration BOOLEAN,
    informationdeclaration BOOLEAN,
    sharingdetailsdeclaration BOOLEAN,
    socialmediaconsentdeclaration BOOLEAN,
    agreeTab0 BOOLEAN,
    agreeTab1 BOOLEAN,
    numCows INTEGER,
    numBullsOxenCalves INTEGER,
    area VARCHAR(255),
    visitorCapacity INTEGER,
    teamMembers INTEGER,
    volunteers INTEGER,
    otherActivities TEXT,
    uniqueInitiative TEXT,
    awards TEXT,
    participation TEXT,
    eventDays VARCHAR(20),
    customDays VARCHAR(255),
    customDaysReason TEXT,
    visitTimingType VARCHAR(20),
    allDayFrom TIME,
    allDayTo TIME,
    slotMorningFrom TIME,
    slotMorningTo TIME,
    slotAfternoonFrom TIME,
    slotAfternoonTo TIME,
    slotEveningFrom TIME,
    slotEveningTo TIME,
    activitiesOnSite TEXT[],           -- Array of strings
    activitiesOnSiteOther VARCHAR(255),
    activitiesLocality TEXT[],         -- Array of strings
    activitiesLocalityOther VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);